---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[prebuilt_postgresql::client]
      - recipe[prebuilt_postgresql::server]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      prebuilt_postgresql:
        version: 9.6.8
